general:
  prefix: '&7[&a&lMEME&7]'

message:
  verbose: '&a%player% &6is flagging &a%check% &7(&a%type%&7) &7[&a%violation%&7] &7(&a%identifiers%&7)'
  violation: '&a%player%&7 is using &a%check% &7(&a%type%&7) &7[&a%violation%&7] &7(&a%identifiers%&7)'
  evaluator: '&a%player%&7 is hacking (&aProbability&7:&a %evaluator%&7)'
  ban: '&7[&a&lMEME&7] &aUnfair Advantage'
  no-permisison: '&4No permissions'
  invalid-player: '%prefix% &cInvalid player!'